In [29]:
import pandas as pd

In [30]:
app=pd.read_csv('D:\python notes\Python\data cleaning and visualization\googleplaystore.csv')

In [31]:
app.head(2)#default will be top 5 entries

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,7-Jan-18,1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,15-Jan-18,2.0.0,4.0.3 and up

In [32]:
app.tail(2)#bottoms two

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,19-Jan-15,Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,25-Jul-18,Varies with device,Varies with device

In [33]:
modifying_dataframe=pd.read_csv('D:\python notes\Python\data cleaning and visualization\googleplaystore.csv', header=1,index_col=0)
#header allows you to specify which row will be used as coloumns name for your data frame by default its value is zero
#index_col allows you to specify which coloumn to be used as the index of dataframe sort of primary key
#only  App contains unique values thats why i am making it index coloumn

In [34]:
modifying_dataframe.head(2)

,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,7-Jan-18,1.0.0,4.0.3 and up
Photo Editor & Candy Camera & Grid & ScrapBook,,,,,,,,,,,,
Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,15-Jan-18,2.0.0,4.0.3 and up
"U Launcher Lite – FREE Live Cool Themes, Hide Apps",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,1-Aug-18,1.2.4,4.0.3 and up

In [35]:
app.info()#info about dataset

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10841 non-null  object
 1   Category        10841 non-null  object
 2   Rating          9367 non-null   float64
 3   Reviews         10841 non-null  object
 4   Size            10841 non-null  object
 5   Installs        10841 non-null  object
 6   Type            10840 non-null  object
 7   Price           10841 non-null  object
 8   Content Rating  10840 non-null  object
 9   Genres          10841 non-null  object
 10  Last Updated    10841 non-null  object
 11  Current Ver     10833 non-null  object
 12  Android Ver     10838 non-null  object
dtypes: float64(1), object(12)
memory usage: 1.1+ MB

In [36]:
app.describe()#gives info of numeric values 
#like rating coloumn is in numeric and its totak entries are 10841 so 
#count =10841-9367=1474(subtracting null values )

            Rating
count  9367.000000
mean      4.193338
std       0.537431
min       1.000000
25%       4.000000
50%       4.300000
75%       4.500000
max      19.000000

Acessing a particular row

In [37]:
app.iloc[2] # It will select the third row of our data



#iloc() Using the iloc method in python, we can easily retrieve any particular value from a row or column by using index values
# data2=data.iloc[:10,9:12]
# data2

App               U Launcher Lite – FREE Live Cool Themes, Hide ...
Category                                             ART_AND_DESIGN
Rating                                                          4.7
Reviews                                                       87510
Size                                                           8.7M
Installs                                                 5,000,000+
Type                                                           Free
Price                                                             0
Content Rating                                             Everyone
Genres                                                 Art & Design
Last Updated                                               1-Aug-18
Current Ver                                                   1.2.4
Android Ver                                            4.0.3 and up
Name: 2, dtype: object

In [38]:
# If we want to use the index coloumn which we defined than we have to use loc
modifying_dataframe.loc['iHoroscope - 2018 Daily Horoscope & Astrology']# this is app coloumn's value  here
#So this will show you all coloumns data in that specific row

ART_AND_DESIGN             LIFESTYLE
4.1                              4.5
159                           398307
19M                              19M
10,000+                  10,000,000+
Free                            Free
0                                  0
Everyone                    Everyone
Art & Design               Lifestyle
7-Jan-18                   25-Jul-18
1.0.0             Varies with device
4.0.3 and up      Varies with device
Name: iHoroscope - 2018 Daily Horoscope & Astrology, dtype: object

Acessing a particular coloumn

In [39]:
app['Genres'].head()#Acessing single coloumn by his name
# app.Genres.head()

0                 Art & Design
1    Art & Design;Pretend Play
2                 Art & Design
3                 Art & Design
4      Art & Design;Creativity
Name: Genres, dtype: object

Unique values in specific Coloumn

In [40]:
app['App'].unique()

array(['Photo Editor & Candy Camera & Grid & ScrapBook',
       'Coloring book moana',
       'U Launcher Lite – FREE Live Cool Themes, Hide Apps', ...,
       'Parkinson Exercices FR', 'The SCP Foundation DB fr nn5n',
       'iHoroscope - 2018 Daily Horoscope & Astrology'], dtype=object)

How many types of value (with their quantity ) each coloumns contains

In [41]:
app['Content Rating'].value_counts()

Everyone           8714
Teen               1208
Mature 17+          499
Everyone 10+        414
Adults only 18+       3
Unrated               2
Name: Content Rating, dtype: int64

Which app has Highest reviews

In [42]:
# app.Reviews.max()# it will give you max count exist in  reviews  column


highestReviewdProduct=app.Reviews.max()
app[app['Reviews']==highestReviewdProduct]# if reviews coloumn matches the highest number return that specific row 

#below one will give only one coloumn data what you want
# app.loc[app['Reviews']==highestReviewdProduct,'App']

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
2989,GollerCepte Live Score,SPORTS,4.2,9992,31M,"1,000,000+",Free,0,Everyone,Sports,23-May-18,6.5,4.1 and up

Checking top rated Apps

In [43]:
top_rated=app.nlargest(10,'Rating')
# top_rated
# I am not calling top_rated Rating coloumn need to be cleaned

### Inserting a new coloumn

In [80]:
app['Type And Reviews']=app['Type']+" " +app['Reviews']

In [81]:
app.head(2)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Type And Reviews,S NO
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,7-Jan-18,1.0.0,4.0.3 and up,Free 159,1
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,15-Jan-18,2.0.0,4.0.3 and up,Free 967,2

In [89]:
#rename the coloumn
app.rename(
    columns={"Type And Reviews":"Unnecessary"},inplace=True)
app

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Unnecessary,S NO
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,7-Jan-18,1.0.0,4.0.3 and up,Free 159,1
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,15-Jan-18,2.0.0,4.0.3 and up,Free 967,2
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,1-Aug-18,1.2.4,4.0.3 and up,Free 87510,3
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,8-Jun-18,Varies with device,4.2 and up,Free 215644,4
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,20-Jun-18,1.1,4.4 and up,Free 967,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone,Education,25-Jul-17,1.48,4.1 and up,Free 38,10837
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,6-Jul-18,1,4.1 and up,Free 4,10838
10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0,Everyone,Medical,20-Jan-17,1,2.2 and up,Free 3,10839
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,19-Jan-15,Varies with device,Varies with device,Free 114,10840
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,25-Jul-18,Varies with device,Varies with device,Free 398307,10841

In [90]:
#delete the coloumn 
app.drop('Unnecessary', axis=1,inplace=True)

## Inserting a S NO coloumn that will contain a unique value

In [92]:
app['S NO']=range(1,len(app.index)+1)

In [93]:
app.iloc[0:2,10:16]

  Last Updated Current Ver   Android Ver  S NO
0     7-Jan-18       1.0.0  4.0.3 and up     1
1    15-Jan-18       2.0.0  4.0.3 and up     2